package school.sptech.megusta.dto.relatorio;

public enum TipoItemRelatorio {

    INSUMOS_MAIS_UTILIZADOS,
    QUANTIDADE_TOTAL_CONSUMIDA_POR_INSUMO,
    CONSUMO_POR_CATEGORIA,
    MEDIA_CONSUMO,

    SAIDAS_POR_PERIODO,
    MOTIVOS_SAIDAS,
    PERDAS,

    ENTRADAS_POR_PERIODO,
    VALOR_TOTAL_ENTRADAS,
    FORNECEDORES_MAIS_ABASTECERAM,

    ITENS_PROXIMOS_VENCIMENTO,
    ITENS_VENCIDOS,

    ESTOQUE_ATUAL,
    ITENS_ABAIXO_ESTOQUE_MINIMO,

    ENTRADA_SAIDA_INSUMO
}